export type CatalogCollection = { id: number; name: string; cats: string[] };

export const COLLECTION_CATEGORIES = [
  "Sagas",
  "Superheroes",
  "Action",
  "Adventure",
  "Sci-Fi",
  "Fantasy",
  "Animation",
  "Horror",
  "Comedy",
  "Crime",
] as const;

export const COLLECTIONS_CATALOG: CatalogCollection[] = [
  { id: 10, name: "Star Wars", cats: ["Sagas", "Sci-Fi"] },
  { id: 1241, name: "Harry Potter", cats: ["Sagas", "Fantasy"] },
  { id: 119, name: "The Lord of the Rings", cats: ["Sagas", "Fantasy"] },
  { id: 121938, name: "The Hobbit", cats: ["Sagas", "Fantasy"] },
  { id: 263, name: "The Dark Knight Trilogy", cats: ["Superheroes", "Crime"] },
  { id: 328, name: "Jurassic Park", cats: ["Adventure", "Sci-Fi"] },
  { id: 87096, name: "Avatar", cats: ["Sagas", "Sci-Fi"] },
  { id: 9485, name: "The Fast and the Furious", cats: ["Action"] },
  { id: 87359, name: "Mission: Impossible", cats: ["Action"] },
  { id: 645, name: "James Bond 007", cats: ["Action"] },
  { id: 295, name: "Pirates of the Caribbean", cats: ["Adventure", "Fantasy"] },
  { id: 2344, name: "The Matrix", cats: ["Sci-Fi", "Action"] },
  { id: 404609, name: "John Wick", cats: ["Action"] },
  { id: 84, name: "Indiana Jones", cats: ["Adventure"] },
  { id: 8091, name: "Alien", cats: ["Sci-Fi", "Horror"] },
  { id: 399, name: "Predator", cats: ["Sci-Fi", "Action"] },
  { id: 528, name: "The Terminator", cats: ["Sci-Fi", "Action"] },
  { id: 264, name: "Back to the Future", cats: ["Sci-Fi", "Adventure", "Comedy"] },
  { id: 131635, name: "The Hunger Games", cats: ["Sagas", "Sci-Fi"] },
  { id: 1575, name: "Rocky", cats: ["Action"] },
  { id: 8945, name: "Mad Max", cats: ["Action", "Sci-Fi"] },
  { id: 1570, name: "Die Hard", cats: ["Action"] },
  { id: 86311, name: "The Avengers", cats: ["Superheroes"] },
  { id: 284433, name: "Guardians of the Galaxy", cats: ["Superheroes", "Comedy"] },
  { id: 448150, name: "Deadpool", cats: ["Superheroes", "Comedy"] },
  { id: 556, name: "Spider-Man", cats: ["Superheroes"] },
  { id: 748, name: "X-Men", cats: ["Superheroes"] },
  { id: 8650, name: "Transformers", cats: ["Action", "Sci-Fi"] },
  { id: 726871, name: "Dune", cats: ["Sagas", "Sci-Fi"] },
  { id: 173710, name: "Planet of the Apes", cats: ["Sci-Fi"] },
  { id: 31562, name: "The Bourne Series", cats: ["Action"] },
  { id: 134004, name: "Taken", cats: ["Action"] },
  { id: 126125, name: "The Expendables", cats: ["Action"] },
  { id: 2883, name: "Kill Bill", cats: ["Action", "Crime"] },
  { id: 2980, name: "Ghostbusters", cats: ["Comedy", "Fantasy"] },
  { id: 86055, name: "Men in Black", cats: ["Sci-Fi", "Comedy"] },
  { id: 304, name: "Ocean's", cats: ["Crime", "Comedy"] },
  { id: 138101, name: "Sherlock Holmes", cats: ["Crime", "Adventure"] },
  { id: 230, name: "The Godfather", cats: ["Crime"] },
  { id: 8675, name: "The Mummy", cats: ["Adventure", "Horror"] },
  { id: 313086, name: "The Conjuring Universe", cats: ["Horror"] },
  { id: 91361, name: "Halloween", cats: ["Horror"] },
  { id: 656, name: "Saw", cats: ["Horror"] },
  { id: 2602, name: "Scream", cats: ["Horror"] },
  { id: 8581, name: "A Nightmare on Elm Street", cats: ["Horror"] },
  { id: 17255, name: "Resident Evil", cats: ["Horror", "Action"] },
  { id: 720879, name: "Sonic the Hedgehog", cats: ["Animation", "Adventure"] },
  { id: 10194, name: "Toy Story", cats: ["Animation"] },
  { id: 468222, name: "The Incredibles", cats: ["Animation", "Superheroes"] },
  { id: 137697, name: "Finding Nemo", cats: ["Animation"] },
  { id: 137696, name: "Monsters, Inc.", cats: ["Animation"] },
  { id: 87118, name: "Cars", cats: ["Animation"] },
  { id: 386382, name: "Frozen", cats: ["Animation", "Fantasy"] },
  { id: 2150, name: "Shrek", cats: ["Animation", "Comedy"] },
  { id: 14890, name: "Madagascar", cats: ["Animation", "Comedy"] },
  { id: 89137, name: "How to Train Your Dragon", cats: ["Animation", "Fantasy"] },
  { id: 77816, name: "Kung Fu Panda", cats: ["Animation", "Comedy"] },
  { id: 86066, name: "Despicable Me", cats: ["Animation", "Comedy"] },
  { id: 8354, name: "Ice Age", cats: ["Animation", "Comedy"] },
  { id: 420, name: "The Chronicles of Narnia", cats: ["Fantasy", "Adventure"] },
  { id: 0, name: "Star Trek", cats: ["Sci-Fi", "Sagas"] },
  { id: 0, name: "Rambo", cats: ["Action"] },
  { id: 0, name: "Lethal Weapon", cats: ["Action", "Crime"] },
  { id: 0, name: "Bad Boys", cats: ["Action", "Comedy"] },
  { id: 0, name: "Rush Hour", cats: ["Action", "Comedy"] },
  { id: 0, name: "The Equalizer", cats: ["Action"] },
  { id: 0, name: "Top Gun", cats: ["Action"] },
  { id: 0, name: "Creed", cats: ["Action"] },
  { id: 0, name: "The Karate Kid", cats: ["Action", "Adventure"] },
  { id: 0, name: "Blade", cats: ["Superheroes", "Horror"] },
  { id: 0, name: "Hellboy", cats: ["Superheroes", "Fantasy"] },
  { id: 0, name: "Wonder Woman", cats: ["Superheroes"] },
  { id: 0, name: "Aquaman", cats: ["Superheroes"] },
  { id: 0, name: "Venom", cats: ["Superheroes"] },
  { id: 0, name: "Thor", cats: ["Superheroes"] },
  { id: 0, name: "Captain America", cats: ["Superheroes"] },
  { id: 0, name: "Iron Man", cats: ["Superheroes"] },
  { id: 0, name: "Ant-Man", cats: ["Superheroes", "Comedy"] },
  { id: 0, name: "Doctor Strange", cats: ["Superheroes", "Fantasy"] },
  { id: 0, name: "Black Panther", cats: ["Superheroes"] },
  { id: 0, name: "Fantastic Beasts", cats: ["Fantasy", "Sagas"] },
  { id: 0, name: "The Maze Runner", cats: ["Sci-Fi", "Adventure"] },
  { id: 0, name: "Divergent", cats: ["Sci-Fi", "Adventure"] },
  { id: 0, name: "Percy Jackson", cats: ["Fantasy", "Adventure"] },
  { id: 0, name: "The Twilight Saga", cats: ["Fantasy", "Sagas"] },
  { id: 0, name: "Pacific Rim", cats: ["Sci-Fi", "Action"] },
  { id: 0, name: "Cloverfield", cats: ["Sci-Fi", "Horror"] },
  { id: 0, name: "A Quiet Place", cats: ["Horror", "Sci-Fi"] },
  { id: 0, name: "The Purge", cats: ["Horror"] },
  { id: 0, name: "Insidious", cats: ["Horror"] },
  { id: 0, name: "Annabelle", cats: ["Horror"] },
  { id: 0, name: "Final Destination", cats: ["Horror"] },
  { id: 0, name: "Paranormal Activity", cats: ["Horror"] },
  { id: 0, name: "Child's Play", cats: ["Horror"] },
  { id: 0, name: "The Texas Chainsaw Massacre", cats: ["Horror"] },
  { id: 0, name: "Evil Dead", cats: ["Horror"] },
  { id: 0, name: "Underworld", cats: ["Horror", "Action"] },
  { id: 0, name: "Godzilla", cats: ["Sci-Fi", "Action"] },
  { id: 0, name: "Knives Out", cats: ["Crime", "Comedy"] },
  { id: 0, name: "Now You See Me", cats: ["Crime"] },
  { id: 0, name: "National Treasure", cats: ["Adventure"] },
  { id: 0, name: "Night at the Museum", cats: ["Comedy", "Fantasy"] },
  { id: 0, name: "21 Jump Street", cats: ["Comedy", "Action"] },
  { id: 0, name: "Pitch Perfect", cats: ["Comedy"] },
  { id: 0, name: "Mamma Mia!", cats: ["Comedy"] },
  { id: 0, name: "Bridget Jones", cats: ["Comedy"] },
  { id: 0, name: "Hotel Transylvania", cats: ["Animation", "Comedy"] },
  { id: 0, name: "The Secret Life of Pets", cats: ["Animation", "Comedy"] },
  { id: 0, name: "Sing", cats: ["Animation"] },
  { id: 0, name: "Trolls", cats: ["Animation"] },
  { id: 0, name: "Minions", cats: ["Animation", "Comedy"] },
  { id: 0, name: "The Lego Movie", cats: ["Animation", "Comedy"] },
  { id: 0, name: "Spider-Man: Spider-Verse", cats: ["Animation", "Superheroes"] },
  { id: 0, name: "Kingsman", cats: ["Action", "Comedy"] },
  { id: 0, name: "Sicario", cats: ["Crime", "Action"] },
  { id: 0, name: "Zoolander", cats: ["Comedy"] },
  { id: 0, name: "Austin Powers", cats: ["Comedy"] },
  { id: 0, name: "Scary Movie", cats: ["Comedy", "Horror"] },
  { id: 0, name: "The Hangover", cats: ["Comedy"] },
  { id: 0, name: "Jackass", cats: ["Comedy"] },
  { id: 0, name: "Magic Mike", cats: ["Comedy"] },
  { id: 0, name: "Fifty Shades", cats: ["Sagas"] },
  { id: 0, name: "After", cats: ["Sagas"] },
  { id: 0, name: "To All the Boys", cats: ["Comedy"] },
  { id: 0, name: "The Princess Diaries", cats: ["Comedy"] },
];
